version: '3.4'
services:
  db:
    image: postgres
    container_name: exchange_pq
    restart: always
    volumes:
      - ./data/volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: exchange
      POSTGRES_USER: exchange
      POSTGRES_PASSWORD: exchange_AA9944

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: exchange_zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./data/volumes/log_zookeeper:/var/log/zookeeper

  kafka:
    image: wurstmeister/kafka:latest
    container_name: exchange_kafka
    restart: always
    logging:
      options:
        max-size: 10m
    ports:
      - "9092:9092"
    volumes:
      - ./data/volumes/log_kafka:/var/log/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
